title: Odhko
description: Fiches de révision de Vishwaraj Shabadi

plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM # GitHub Flavored Markdown

remote_theme: lewismiddleton/cayman-dark

# navigation:
#   name_over_title: false
#   # toc_parameter:

show_downloads: false
google_analytics: G-TLQD7X9Z6C
