remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM # GitHub Flavored Markdown

title: My GitHub Pages Site
description: A site with LaTeX rendered using MathJax
